# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='id_product',
            new_name='product',
        ),
    ]
