# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='url',
            field=models.CharField(default='asda', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
